//! Deterministic, provider-neutral workflow evidence bundles.

use sema_workflow::approval::{
    self, ApprovalDecision, ApprovalDecisionKind, ApprovalRequest, ApprovalResolution,
};
use serde::Serialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};

#[derive(Debug, Serialize)]
struct Evidence {
    schema_version: u32,
    run_id: String,
    status: Option<String>,
    metadata: serde_json::Value,
    result: serde_json::Value,
    event_counts: BTreeMap<String, usize>,
    events: Vec<serde_json::Value>,
    approvals: Vec<ApprovalEvidence>,
}

#[derive(Debug, Serialize)]
struct ApprovalEvidence {
    approval_id: String,
    request_digest: String,
    revision: u64,
    phase: String,
    key: String,
    occurrence: u32,
    subject_digest: String,
    reason: String,
    preview: Option<String>,
    requested_at: String,
    status: &'static str,
    decision: Option<ApprovalDecisionEvidence>,
}

#[derive(Debug, Serialize)]
struct ApprovalDecisionEvidence {
    decision_id: String,
    decision: ApprovalDecisionKind,
    actor: String,
    provenance: String,
    comment: Option<String>,
    reason: Option<String>,
    decided_at: String,
}

#[derive(Debug, Serialize)]
struct Manifest {
    schema_version: u32,
    run_id: String,
    files: Vec<ManifestFile>,
}

#[derive(Debug, Serialize)]
struct ManifestFile {
    path: String,
    bytes: usize,
    sha256: String,
}

pub struct ExportedEvidence {
    pub directory: PathBuf,
    pub evidence_json: PathBuf,
    pub evidence_markdown: PathBuf,
    pub manifest_json: PathBuf,
}

pub fn export(
    runs_root: &Path,
    run_id: &str,
    output_directory: Option<&Path>,
) -> io::Result<ExportedEvidence> {
    validate_run_id(run_id)?;
    let run_directory = runs_root.join(run_id);
    if !run_directory.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("workflow run not found: {}", run_directory.display()),
        ));
    }
    let output_directory = output_directory
        .map(Path::to_path_buf)
        .unwrap_or_else(|| run_directory.join("evidence"));
    fs::create_dir_all(&output_directory)?;

    let metadata = read_json_or_null(&run_directory.join("metadata.json"))?;
    let result = read_json_or_null(&run_directory.join("result.json"))?;
    let approval_resolutions = approval::list_requests(runs_root, run_id)?;
    let approvals = approval_resolutions
        .iter()
        .map(ApprovalEvidence::from)
        .collect();
    let journal_paths = journal_paths(&run_directory)?;
    let mut events = Vec::new();
    let mut event_counts = BTreeMap::new();
    for path in &journal_paths {
        for line in fs::read_to_string(path)?.lines() {
            if line.trim().is_empty() {
                continue;
            }
            let event: serde_json::Value = serde_json::from_str(line).map_err(|error| {
                io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("{}: {error}", path.display()),
                )
            })?;
            if let Some(kind) = event.get("event").and_then(serde_json::Value::as_str) {
                *event_counts.entry(kind.to_string()).or_insert(0) += 1;
            }
            events.push(event);
        }
    }
    let status = result
        .get("status")
        .and_then(serde_json::Value::as_str)
        .map(str::to_string);
    let evidence = Evidence {
        schema_version: 1,
        run_id: run_id.to_string(),
        status,
        metadata,
        result,
        event_counts,
        events,
        approvals,
    };

    let evidence_json = output_directory.join("evidence.json");
    let evidence_markdown = output_directory.join("evidence.md");
    let manifest_json = output_directory.join("manifest.json");
    let json_bytes = serde_json::to_vec_pretty(&evidence).map_err(io::Error::other)?;
    sema_core::fs::AtomicFile::write(&evidence_json, &json_bytes)?;
    let markdown = render_markdown(&evidence);
    sema_core::fs::AtomicFile::write(&evidence_markdown, markdown.as_bytes())?;

    let mut manifest_sources = vec![
        run_directory.join("metadata.json"),
        run_directory.join("result.json"),
    ];
    manifest_sources.extend(journal_paths);
    let mut files = manifest_sources
        .into_iter()
        .filter(|path| path.is_file())
        .map(|path| manifest_file(&path, &run_directory, &output_directory))
        .collect::<io::Result<Vec<_>>>()?;
    for path in approval_sidecar_paths(&run_directory, &approval_resolutions)
        .into_iter()
        .chain([evidence_json.clone(), evidence_markdown.clone()])
    {
        // These files were either signature-validated above or generated by this
        // export. Do not silently omit one if it disappears before hashing.
        files.push(manifest_file(&path, &run_directory, &output_directory)?);
    }
    let manifest = Manifest {
        schema_version: 1,
        run_id: run_id.to_string(),
        files,
    };
    sema_core::fs::AtomicFile::write(
        &manifest_json,
        &serde_json::to_vec_pretty(&manifest).map_err(io::Error::other)?,
    )?;

    Ok(ExportedEvidence {
        directory: output_directory,
        evidence_json,
        evidence_markdown,
        manifest_json,
    })
}

impl From<&ApprovalResolution> for ApprovalEvidence {
    fn from(resolution: &ApprovalResolution) -> Self {
        let (request, status, decision) = match resolution {
            ApprovalResolution::Pending(request) => (request, "pending", None),
            ApprovalResolution::Approved(request, decision) => {
                (request, "approved", Some(decision))
            }
            ApprovalResolution::Rejected(request, decision) => {
                (request, "rejected", Some(decision))
            }
        };
        Self::new(request, status, decision)
    }
}

impl ApprovalEvidence {
    fn new(
        request: &ApprovalRequest,
        status: &'static str,
        decision: Option<&ApprovalDecision>,
    ) -> Self {
        Self {
            approval_id: request.approval_id.clone(),
            request_digest: request.request_digest.clone(),
            revision: request.revision,
            phase: request.phase.clone(),
            key: request.key.clone(),
            occurrence: request.occurrence,
            subject_digest: request.subject_digest.clone(),
            reason: request.reason.clone(),
            preview: request.preview.clone(),
            requested_at: request.requested_at.clone(),
            status,
            decision: decision.map(ApprovalDecisionEvidence::from),
        }
    }
}

impl From<&ApprovalDecision> for ApprovalDecisionEvidence {
    fn from(decision: &ApprovalDecision) -> Self {
        Self {
            decision_id: decision.decision_id.clone(),
            decision: decision.decision,
            actor: decision.actor.clone(),
            provenance: decision.provenance.clone(),
            comment: decision.comment.clone(),
            reason: decision.reason.clone(),
            decided_at: decision.decided_at.clone(),
        }
    }
}

fn approval_sidecar_paths(
    run_directory: &Path,
    resolutions: &[ApprovalResolution],
) -> Vec<PathBuf> {
    resolutions
        .iter()
        .flat_map(|resolution| {
            let (request, has_decision) = match resolution {
                ApprovalResolution::Pending(request) => (request, false),
                ApprovalResolution::Approved(request, _)
                | ApprovalResolution::Rejected(request, _) => (request, true),
            };
            let request_path = approval::request_path(run_directory, &request.approval_id);
            let decision_path =
                has_decision.then(|| approval::decision_path(run_directory, &request.approval_id));
            std::iter::once(request_path).chain(decision_path)
        })
        .collect()
}

fn validate_run_id(run_id: &str) -> io::Result<()> {
    let mut components = Path::new(run_id).components();
    let valid = matches!(components.next(), Some(Component::Normal(_)))
        && components.next().is_none()
        && run_id != "."
        && run_id != "..";
    if valid {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "run id must be exactly one safe path component",
        ))
    }
}

fn read_json_or_null(path: &Path) -> io::Result<serde_json::Value> {
    match fs::read(path) {
        Ok(bytes) => serde_json::from_slice(&bytes).map_err(|error| {
            io::Error::new(
                io::ErrorKind::InvalidData,
                format!("{}: {error}", path.display()),
            )
        }),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(serde_json::Value::Null),
        Err(error) => Err(error),
    }
}

fn journal_paths(run_directory: &Path) -> io::Result<Vec<PathBuf>> {
    let mut paths = Vec::new();
    let primary = run_directory.join("events.jsonl");
    if primary.is_file() {
        paths.push(primary);
    }
    let mut resumes = fs::read_dir(run_directory)?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.starts_with("events.resume-") && name.ends_with(".jsonl"))
        })
        .collect::<Vec<_>>();
    resumes.sort_by_key(|path| {
        path.file_stem()
            .and_then(|stem| stem.to_str())
            .and_then(|stem| stem.strip_prefix("events.resume-"))
            .and_then(|number| number.parse::<u64>().ok())
            .unwrap_or(u64::MAX)
    });
    paths.extend(resumes);
    Ok(paths)
}

fn render_markdown(evidence: &Evidence) -> String {
    let mut markdown = format!(
        "# Workflow evidence\n\n- Run: `{}`\n- Status: `{}`\n- Events: {}\n\n## Event counts\n\n| Event | Count |\n| --- | ---: |\n",
        evidence.run_id,
        evidence.status.as_deref().unwrap_or("unknown"),
        evidence.events.len()
    );
    for (event, count) in &evidence.event_counts {
        markdown.push_str(&format!("| `{event}` | {count} |\n"));
    }
    if !evidence.approvals.is_empty() {
        markdown.push_str(
            "\n## Human approvals\n\n| Approval | Key | Phase | Status | Actor |\n| --- | --- | --- | --- | --- |\n",
        );
        for approval in &evidence.approvals {
            let actor = approval
                .decision
                .as_ref()
                .map_or("—", |decision| decision.actor.as_str());
            markdown.push_str(&format!(
                "| {} | {} | {} | {} | {} |\n",
                markdown_cell(&approval.approval_id),
                markdown_cell(&approval.key),
                markdown_cell(&approval.phase),
                approval.status,
                markdown_cell(actor),
            ));
        }
    }
    markdown.push_str(
        "\nThe machine-readable bundle is `evidence.json`; file integrity, including validated approval sidecars, is recorded in `manifest.json`.\n",
    );
    markdown
}

fn markdown_cell(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('|', "\\|")
        .replace(['\r', '\n'], " ")
}

fn manifest_file(
    path: &Path,
    run_directory: &Path,
    output_directory: &Path,
) -> io::Result<ManifestFile> {
    let bytes = fs::read(path)?;
    let display = path
        .strip_prefix(run_directory)
        .or_else(|_| path.strip_prefix(output_directory))
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/");
    Ok(ManifestFile {
        path: display,
        bytes: bytes.len(),
        sha256: format!("{:x}", Sha256::digest(&bytes)),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_directory(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "sema-workflow-evidence-{name}-{}",
            std::process::id()
        ))
    }

    #[test]
    fn rejects_path_like_run_ids() {
        assert!(validate_run_id("../run").is_err());
        assert!(validate_run_id("nested/run").is_err());
        assert!(validate_run_id("run-1").is_ok());
    }

    #[test]
    fn exports_ordered_events_and_integrity_manifest() {
        let root = test_directory("bundle");
        let _ = fs::remove_dir_all(&root);
        let run = root.join("run-1");
        fs::create_dir_all(&run).unwrap();
        fs::write(run.join("metadata.json"), r#"{"name":"demo"}"#).unwrap();
        fs::write(run.join("result.json"), r#"{"status":"success"}"#).unwrap();
        fs::write(
            run.join("events.jsonl"),
            "{\"event\":\"run.started\",\"seq\":1}\n",
        )
        .unwrap();
        fs::write(
            run.join("events.resume-1.jsonl"),
            "{\"event\":\"checkpoint\",\"seq\":2}\n",
        )
        .unwrap();

        let bundle = export(&root, "run-1", None).unwrap();
        let evidence: serde_json::Value =
            serde_json::from_slice(&fs::read(&bundle.evidence_json).unwrap()).unwrap();
        assert_eq!(evidence["status"], "success");
        assert_eq!(evidence["event_counts"]["run.started"], 1);
        assert_eq!(evidence["event_counts"]["checkpoint"], 1);
        assert_eq!(evidence["events"][0]["seq"], 1);
        assert_eq!(evidence["events"][1]["seq"], 2);
        assert_eq!(evidence["approvals"], serde_json::json!([]));

        let manifest: serde_json::Value =
            serde_json::from_slice(&fs::read(&bundle.manifest_json).unwrap()).unwrap();
        let files = manifest["files"].as_array().unwrap();
        let evidence_entry = files
            .iter()
            .find(|entry| entry["path"] == "evidence/evidence.json")
            .unwrap();
        let evidence_bytes = fs::read(&bundle.evidence_json).unwrap();
        assert_eq!(
            evidence_entry["sha256"],
            format!("{:x}", Sha256::digest(&evidence_bytes))
        );

        fs::remove_dir_all(&root).unwrap();
    }

    #[test]
    fn exports_validated_approval_summaries_and_sidecars() {
        let root = test_directory("approvals");
        let _ = fs::remove_dir_all(&root);
        let run = root.join("run-1");
        fs::create_dir_all(&run).unwrap();
        fs::write(run.join("metadata.json"), r#"{"name":"release"}"#).unwrap();
        fs::write(run.join("result.json"), r#"{"status":"success"}"#).unwrap();
        fs::write(
            run.join("events.jsonl"),
            "{\"event\":\"approval.applied\",\"seq\":1}\n",
        )
        .unwrap();

        let signing_key = approval::ApprovalSigningKey::generate().unwrap();
        let request = ApprovalRequest::new(approval::NewApprovalRequest {
            run_id: "run-1".to_string(),
            workflow: "release".to_string(),
            code_version: "sha256:code".to_string(),
            args_digest: "sha256:args".to_string(),
            phase: "Review | sign-off".to_string(),
            key: "release-signoff".to_string(),
            occurrence: 1,
            subject_digest: "sha256:subject".to_string(),
            reason: "Publish the release".to_string(),
            preview: Some("release@1.0.0".to_string()),
            requested_at: "2026-08-01T00:00:00Z".to_string(),
            authority_public_key: signing_key.public_key_base64().unwrap(),
        });
        let approval_id = request.approval_id.clone();
        approval::ensure_request(&run, &request).unwrap();
        approval::decide(
            &root,
            "run-1",
            &approval_id,
            &signing_key,
            ApprovalDecisionKind::Approve,
            "release-manager".to_string(),
            "test".to_string(),
            Some("verified".to_string()),
            None,
        )
        .unwrap();

        let bundle = export(&root, "run-1", None).unwrap();
        let evidence: serde_json::Value =
            serde_json::from_slice(&fs::read(&bundle.evidence_json).unwrap()).unwrap();
        assert_eq!(evidence["approvals"][0]["approval_id"], approval_id);
        assert_eq!(evidence["approvals"][0]["status"], "approved");
        assert_eq!(
            evidence["approvals"][0]["decision"]["actor"],
            "release-manager"
        );

        let markdown = fs::read_to_string(&bundle.evidence_markdown).unwrap();
        assert!(markdown.contains("Review \\| sign-off"));
        assert!(markdown.contains("release-manager"));

        let manifest: serde_json::Value =
            serde_json::from_slice(&fs::read(&bundle.manifest_json).unwrap()).unwrap();
        let paths = manifest["files"]
            .as_array()
            .unwrap()
            .iter()
            .filter_map(|entry| entry["path"].as_str())
            .collect::<Vec<_>>();
        assert!(paths.contains(&format!("approvals/{approval_id}.request.json").as_str()));
        assert!(paths.contains(&format!("approvals/{approval_id}.decision.json").as_str()));

        let decision_path = approval::decision_path(&run, &approval_id);
        let mut tampered_decision: serde_json::Value =
            serde_json::from_slice(&fs::read(&decision_path).unwrap()).unwrap();
        tampered_decision["actor"] = serde_json::json!("intruder");
        fs::write(
            decision_path,
            serde_json::to_vec_pretty(&tampered_decision).unwrap(),
        )
        .unwrap();
        let error = export(&root, "run-1", Some(&run.join("tampered-evidence")))
            .err()
            .expect("tampered decision must fail export");
        assert_eq!(error.kind(), io::ErrorKind::InvalidData);

        fs::remove_dir_all(&root).unwrap();
    }
}
