#!/usr/bin/env python3
"""Reuse cargo-dist's generated build job without its publishing jobs."""
from pathlib import Path

root = Path(__file__).resolve().parent.parent
release = (root / '.github/workflows/release.yml').read_text()
start = release.index('  build-local-artifacts:\n')
end = release.index('  # Build and package all the platform-agnostic', start)
build = release[start:end]
# Attestation belongs to the publishing workflow. Validation has read-only permissions.
start = build.index('      - name: Attest\n')
end = build.index('      - id: cargo-dist\n', start)
build = build[:start] + build[end:]
build = build.replace('      "attestations": "write"\n', '').replace('      "id-token": "write"\n', '')
header = '''# Generated by scripts/generate-release-validation.py from release.yml.
# Run dist generate first, then this script. No hosting or publishing jobs.
name: Validate release artifacts
on:
  push:
    branches: ["release/**"]
  workflow_dispatch:
permissions:
  contents: read
concurrency:
  group: release-validation-${{ github.ref }}
  cancel-in-progress: true
jobs:
  plan:
    runs-on: ubuntu-22.04
    outputs:
      val: ${{ steps.plan.outputs.manifest }}
      tag-flag: ${{ steps.plan.outputs.tag-flag }}
      publishing: 'false'
    steps:
      - uses: actions/checkout@v7
      - name: Install dist
        shell: bash
        run: curl --proto '=https' --tlsv1.2 -LsSf https://github.com/axodotdev/cargo-dist/releases/download/v0.30.4/cargo-dist-installer.sh | sh
      - name: Plan without creating a release
        id: plan
        shell: bash
        run: |
          version=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[] | select(.name == "sema-lang") | .version')
          dist plan --tag "v$version" --output-format=json > plan.json
          jq '.ci.github.pr_run_mode = "upload" | .ci.github.artifacts_matrix.include |= map(select(any(.targets[]; endswith("apple-darwin"))))' plan.json > macos-plan.json
          echo "manifest=$(jq -c . macos-plan.json)" >> "$GITHUB_OUTPUT"
          echo "tag-flag=--tag=v$version" >> "$GITHUB_OUTPUT"
          echo "Validated source: $GITHUB_SHA" >> "$GITHUB_STEP_SUMMARY"
'''
footer = '''  check-macos:
    needs: [plan, build-local-artifacts]
    uses: ./.github/workflows/check-macos-artifacts.yml
    with:
      plan: ${{ needs.plan.outputs.val }}
    secrets: inherit
'''
(root / '.github/workflows/validate-release.yml').write_text(header + build + footer)
